name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend to VPS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to VPS and Build
        run: |
          sshpass -p "PAbCptqKYwJ2D43Lx@9X" ssh -o StrictHostKeyChecking=no root@161.248.1.254 << 'EOF'
            # Load nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Use Node.js 20
            nvm use 20
            cd /var/www/netsbaybackend

            # Pull latest changes
            git reset --hard
            git pull origin main

            # Install dependencies
            npm install

            # Run Server
            pm2 restart api || pm2 start npm --name "api" -- start

          EOF

          